name : mirror
on: [push]
jobs:
  to_github:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: run tests
      run: make tests_run
      continue-on-error: false
    - name: clean application
      run: make fclean
      continue-on-error: false
    - name: build application
      run: make
      continue-on-error: false
    - name: run app
      run: ./lem_in
      continue-on-error: false
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ${{ secrets.THE_REPO }}
        ssh_private_key:
          ${{ secrets.THE_KEY }}
